### PR TITLE
Fix for potential issue with context broker policies

### LINKED ISSUE #185: log: /etc/envoy/lua/common.lua:34: attempt to index a nil value
Hi,
When i try to test the policy of create entity with valid token getting weired error that [error][lua] [source/extensions/filters/http/lua/lua_filter.cc:801] script log: /etc/envoy/lua/common.lua:34: attempt to index a nil value

### LINKED ISSUE #186: lua policies should be active only on post requests (since they are linked to resource creation)
https://github.com/orchestracities/anubis/blob/0e3920e47a3a5322cc5c834c784d6c7d9d34706a/config/opa-service/lua/common.lua#L6

### PR DESCRIPTION
**Pull request by Cerfoglg**
## Proposed changes

Checking for post requests to avoid issue with retrieving data

Fixes #186
Fixes #185 

## Types of changes

What types of changes does your code introduce to the project: _Put
an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing
      functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after
creating the PR. If you're unsure about any of them, don't hesitate to
ask. We're here to help! This is simply a reminder of what we are going
to look for before merging your code._

- [x] I have read the [CONTRIBUTING][contrib] doc
- [x] I have signed the [Contributor License Agreement][cla]
- [x] I have updated the [RELEASE NOTES][release]
- [x] I have added tests that prove my fix is effective or that my
      feature works
- [x] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in
      downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion
by explaining why you chose the solution you did and what alternatives
you considered, etc...

[cla]: https://raw.githubusercontent.com/orchestracities/anubis/master/individual_cla.pdf
    "Martel Open Source Software Individual Contributor License Agreement"
[contrib]: https://github.com/orchestracities/anubis/blob/master/CONTRIBUTING.md
    "Contributing to Anubis"
[release]: https://github.com/orchestracities/anubis/blob/master/RELEASE_NOTES.md
    "Anubis Release Notes"

### CODE REVIEW

File: config/opa-service/lua/common.lua [hunk 1]
```diff
@@ -10,14 +10,18 @@ function OBJDEF:context_broker_request(request_handle)
...
+    if content_type == "application/json" then
+      local body = request_handle:body()
+      local body_size = body:length()
+      local body_bytes = body:getBytes(0, body_size)
+      local raw_json_text = tostring(body_bytes)
+      lua_value = JSON:decode(raw_json_text)
+      access_to = lua_value.id
+    end
   end
   request_handle:streamInfo():dynamicMetadata():set("envoy.filters.http.lua", "request.info", {
```
Comment (chicco785) [inline config/opa-service/lua/common.lua:26]: what happens when request.info is not set? would be better to add at least a check on "meta!=null"

**Review by chicco785 — CHANGES_REQUESTED** [review]

**Comment by Cerfoglg** [comment]
This is not a fix for the issue of the token potentially getting dropped as reported by one user, but I was unable to recreate said issue on my side, and I can't locate an exact reason with the code or current setup, so unless we get more information or further test, we can't pinpoint that particular issue. This pull will fix the nil errors of LUA

**Review by c0c0n3 — APPROVED** [review]

**Comment by c0c0n3** [comment]
I have read the CLA Document and I hereby sign the CLA
